version: '2.2'

networks:
  localdev:
    name: localdev
  elastic:
    driver: bridge
  sb:
    driver: bridge

services:

  dev_postgresql:
    image: postgres:14  # Specify PostgreSQL version 13
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgresql/data:/var/lib/postgresql/data
    networks:
      - localdev
   
  dev_mongo_db:
    image: mongo:5.0
    restart: always
    container_name: mongo
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=NileshBlog.Tech
    - MONGO_INITDB_ROOT_PASSWORD=SpeakLouder
    volumes:
    - ./volume/mongo/data:/data/db
    networks:
    - localdev
        
  dev_rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
    - RABBITMQ_DEFAULT_USER=mail    
    - RABBITMQ_DEFAULT_PASS=1q2w3e4r
    - RABBITMQ_DEFAULT_VHOST=mail    
    ports:
    - "15672:15672"
    - "5672:5672"
    networks:
    - localdev
   
  dev_elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    ports:
      - 9200:9200
    volumes:
      - ./volume/elastic:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  dev_kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.3
    ports:
      - 5601:5601
    depends_on:
      - dev_elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic
    volumes:
     - ./volume/kibana:/usr/share/elasticsearch/data